Deployment refactoring

diff --git a/_gunicorn_manager b/_gunicorn_manager
--- a/_gunicorn_manager
+++ b/_gunicorn_manager
@@ -4,17 +4,29 @@
 # This script is used to start/stop/restart the CATCH APIs in production mode
 # ============================================================================
 
-
 # Load vars defined in .env
-eval $(cat .env | sed 's/^/export /')
+$(cat .env | sed 's/^/export /')
 
-# Test if we've already got gunicorn running from this project:
-NUMBER_LAUNCHES=$(ps -ef |grep $PWD"/.venv\/bin\/gunicorn" | wc -l)
+# Determine port
+if [[ $DEPLOYMENT_ENV == 'PROD' ]]; then
+    PORT=5000
+elif [[ $DEPLOYMENT_ENV == 'STAGE' ]]; then
+    PORT=5001
+elif [[ $DEPLOYMENT_ENV == 'DEV' ]]; then
+    PORT=5002
+else
+    echo "DEPLOYMENT_ENV not found/recognized!"
+    exit 1
+fi
+
+# Count how many gunicorn processes are running from this virtual environment:
+GUNICORN_PROCESSES=$(ps -ef | grep $VIRTUAL_ENV"/.venv\/bin\/gunicorn" | wc -l)
 
 d_status() {
 
-    if [[ $NUMBER_LAUNCHES -gt 0 ]]; then
-        echo "Gunicorn is running with "$NUMBER_LAUNCHES" workers."
+    if [[ $GUNICORN_PROCESSES -gt 0 ]]; then
+        echo "Gunicorn is running with "$GUNICORN_PROCESSES" workers."
+        echo "Parent PID: $(cat .pid.txt)"
     else
         echo "No gunicorn process is running from this project's virtual environment at the moment."
     fi
@@ -22,22 +34,22 @@ d_status() {
 
 d_start() {
 
-    if [[ $NUMBER_LAUNCHES -gt 0 ]]; then
-        echo "This API is already running in production; cancelling start!"
+    if [[ $GUNICORN_PROCESSES -gt 0 ]]; then
+        d_status
+        echo "Cancelling start!"
     else
         ### Enter src, start gunicorn, exit
-        echo "--------------"
-        echo "This API is not running; begin workers in production!"
         cd src
-        echo $PWD
-        ### Set running mode to production and start gunicorn
+        echo "-----------------------------------------------------"
+        echo "This API is not running; begin workers in production!"
         gunicorn app_entry:flask_app \
-            --config ..\/gunicorn.config.py \
+            --config ..\/.gunicorn.config.py \
             --pid ..\/.pid.txt \
-            --daemon \
-            --name $PROCESS_NAME --bind '127.0.0.1:5001'
+            --name $APP_NAME \
+            --bind '127.0.0.1:5000' \
+            --daemon
+        echo "-----------------------------------------------------"
         cd ..
-        echo "--------------"
     fi
 }
 
@@ -58,51 +70,43 @@ d_stop() {
 }
 
 d_restart() {
-    if [ -e $PIDFILE ]; then
+    if [ -e $PWD/.pid.txt ]; then
         cp .pid.txt .pid-old.txt
         # Reexec a new master with new workers
-        kill -s USR2 `cat .pid.txt`
+        kill -s USR2 $(cat .pid.txt)
+        sleep 1
         # Graceful stop old workers
-        kill -s WINCH `cat .pid-old.txt`
+        kill -s WINCH $(cat .pid-old.txt)
+        sleep 1
         # Graceful stop old master
-        kill -s QUIT `cat .pid-old.txt`
-        # sleep 10
+        kill -s QUIT $(cat .pid-old.txt)
+        sleep 1
     else
         echo "No file '.pid.txt' found! Try starting the API:"
-        if [[ $NUMBER_LAUNCHES -gt 0 ]]; then
+        if [[ $GUNICORN_PROCESSES -gt 0 ]]; then
             echo "This API is already running in production; cancelling start!"
             echo "Something is messed up here; need to send notification to web master!"
         else
-            ### Enter src, start gunicorn, exit
-            cd src
-            echo $PWD
-            ### Set running mode to production and start gunicorn
-            gunicorn app_entry:flask_app \
-                --config ..\/gunicorn.config.py \
-                --pid ..\/.pid.txt \
-                --daemon \
-                --name $PROCESS_NAME --bind '127.0.0.1:5001'
-            cd ..
-            echo "--------------"
+            d_start
         fi
     fi
 }
 
 case $1 in
-    status)
+status)
     d_status
     ;;
-    start)
+start)
     d_start
     ;;
-    stop)
+stop)
     d_stop
     ;;
-    restart)
+restart)
     d_restart
     ;;
-    *)
-    echo "usage: $NAME {status|start|stop|restart}"
+*)
+    echo "usage: $0 {status|start|stop|restart}"
     exit 1
     ;;
 esac
